version: '3'
services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./app:/src/pants/app:z
        depends_on:
            - view
        command: make fresh
    view:
        build:
            context: ./view
            dockerfile: Dockerfile
        volumes:
            - ./app/public:/src/pants/view/public:z
            - ./view:/src/pants/view:z
